version: '3'

services:
  gocd-server:
    build:
      context: ./server
      args:
        - GO_VERSION=17.1.0-4511
        - DOWNLOAD_URL=https://download.gocd.io/binaries
    environment:
      - MSG_TIME=0
    volumes:
      - ./server/config:/var/lib/go-server/config/
    ports:
      - 8153:8153
      - 8154:8154

  gocd-server-backup:
    build:
      context: ./server-backup
    volumes:
      - ./server-backup/data:/var/lib/go-server/artifacts/serverBackups/
    links:
      - gocd-server:gocd-server

  docker-in-docker:
    build:
      context: ./docker-in-docker
    cap_add:
    - ALL
    privileged: true
    environment:
      - DOCKER_CONTENT_TRUST=1

  gocd-agent:
    build:
      context: ./agent
    environment:
      - GO_SERVER_URL=https://gocd-server:8154/go
      - DOCKER_HOST=docker-in-docker
    links:
      - gocd-server:gocd-server
      - docker-in-docker:docker-in-docker
